// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvQZ8X9Y2W3E4R5T6U7V8W9X0Y1Z2A3B4C',
    appId: '1:100517466595833004377:web:abc123def456ghi789jkl',
    messagingSenderId: '100517466595833004377',
    projectId: 'sangam-6529f',
    authDomain: 'sangam-6529f.firebaseapp.com',
    storageBucket: 'sangam-6529f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvQZ8X9Y2W3E4R5T6U7V8W9X0Y1Z2A3B4C',
    appId: '1:100517466595833004377:android:abc123def456ghi789jkl',
    messagingSenderId: '100517466595833004377',
    projectId: 'sangam-6529f',
    storageBucket: 'sangam-6529f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvQZ8X9Y2W3E4R5T6U7V8W9X0Y1Z2A3B4C',
    appId: '1:100517466595833004377:ios:abc123def456ghi789jkl',
    messagingSenderId: '100517466595833004377',
    projectId: 'sangam-6529f',
    storageBucket: 'sangam-6529f.appspot.com',
    iosBundleId: 'com.example.sangamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvQZ8X9Y2W3E4R5T6U7V8W9X0Y1Z2A3B4C',
    appId: '1:100517466595833004377:ios:abc123def456ghi789jkl',
    messagingSenderId: '100517466595833004377',
    projectId: 'sangam-6529f',
    storageBucket: 'sangam-6529f.appspot.com',
    iosBundleId: 'com.example.sangamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvQZ8X9Y2W3E4R5T6U7V8W9X0Y1Z2A3B4C',
    appId: '1:100517466595833004377:web:abc123def456ghi789jkl',
    messagingSenderId: '100517466595833004377',
    projectId: 'sangam-6529f',
    authDomain: 'sangam-6529f.firebaseapp.com',
    storageBucket: 'sangam-6529f.appspot.com',
  );
}
